/*
Problem Statement

Kajal is analyzing a sequence generated by a data transmission system.

According to the system's design, every number in the sequence should appear exactly twice.
However, due to transmission errors, one number appears only once while all other numbers
continue to appear exactly twice.

Instead of reporting the faulty number directly, Kajal wants to determine its position
in the sorted sequence.

Help Kajal find the unique number and determine its position after the sequence is sorted
in non-decreasing order.

Positions are 1-indexed.

Input Format
First line contains an integer N.
Second line contains N space-separated integers.

Output Format
Print two space-separated integers:
UniqueNumber Position

Example
Input:
7
4 2 1 2 1 4 9

Output:
9 7
*/

import java.util.*;

public class Main {
    public static void main(String[] args) {
        Scanner sc = new Scanner(System.in);

        int n = sc.nextInt();
        int[] arr = new int[n];
        int uniqueNum = 0;

        for (int i = 0; i < n; i++) {
            arr[i] = sc.nextInt();
            uniqueNum ^= arr[i];
        }

        int smallerCount = 0;

        for (int num : arr) {
            if (num < uniqueNum) {
                smallerCount++;
            }
        }

        int position = smallerCount + 1;

        System.out.println(uniqueNum + " " + position);

        sc.close();
    }
}
